Added linux-musl packaging and tests to GHA workflow

diff --git a/.github/workflows/rake.yml b/.github/workflows/rake.yml
--- a/.github/workflows/rake.yml
+++ b/.github/workflows/rake.yml
@@ -17,6 +17,7 @@ concurrency:
   cancel-in-progress: true
 
 env:
+  RUBYGEM_VER: 3.4.22
   BUNDLER_VER: 2.4.22
 # Forcing bundler version to ensure that it is consistent everywhere and
 # does not cause bundler gem reinstalls
@@ -44,39 +45,6 @@ jobs:
 
       - name: Rubocop
         run: bundle exec rake rubocop
-
-  rake-alpine:
-    name: test on ${{ image }}
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        ruby: [ '3.2', '3.1', '3.0', '2.7' ]
-    container: ruby:${{ matrix.ruby }}-alpine
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
-
-      - name: Bundle
-        run: bundle install --jobs 4 --retry 3
-
-      - name: Process cache
-        uses: actions/cache@v4
-        id: cache
-        with:
-          path: lib/expressir/express/express_parser.*
-          key: v4-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('ext/express_parser/extconf.rb', 'ext/express_parser/antlrgen/**', 'ext/express_parser/express_parser.cpp', '.git/modules/ext/express_parser/antlr4-upstream/HEAD') }}
-
-      - name: Build native extension
-        if: steps.cache.outputs.cache-hit != 'true'
-        run: bundle exec rake compile
-
-      - name: Run tests
-        run: |
-          bundle exec rake
-          cat .rspec_status
 
   rake:
     name: test on ruby-${{ matrix.ruby }} ${{ matrix.os }}
@@ -116,6 +84,49 @@ jobs:
         with:
           path: lib/expressir/express/express_parser.*
           key: v4-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('ext/express_parser/extconf.rb', 'ext/express_parser/antlrgen/**', 'ext/express_parser/express_parser.cpp', '.git/modules/ext/express_parser/antlr4-upstream/HEAD') }}
+
+      - name: Build native extension
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: bundle exec rake compile
+
+      - name: Run tests
+        run: |
+          bundle exec rake
+          cat .rspec_status
+
+  rake-alpine:
+    name: test on ruby-${{ matrix.ruby }} alpine container
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        ruby: [ '3.2', '3.1', '3.0', '2.7' ]
+    container: ruby:${{ matrix.ruby }}-alpine
+    steps:
+      - name: Install packages
+        run: |
+          apk --no-cache --upgrade add build-base git bash tar
+
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Upgrade RubyGems
+        if: matrix.ruby == '3.0' || matrix.ruby == '2.7'
+        run: gem update --system ${{ env.RUBYGEM_VER }} --no-document
+
+      - name: Bundle
+        run: |
+          git config --global --add safe.directory $PWD
+          bundle install --jobs 4 --retry 3
+
+      - name: Process cache
+        uses: actions/cache@v4
+        id: cache
+        with:
+          path: lib/expressir/express/express_parser.*
+          key: v4-alpine-${{ matrix.ruby }}-${{ hashFiles('ext/express_parser/extconf.rb', 'ext/express_parser/antlrgen/**', 'ext/express_parser/express_parser.cpp', '.git/modules/ext/express_parser/antlr4-upstream/HEAD') }}
 
       - name: Build native extension
         if: steps.cache.outputs.cache-hit != 'true'
@@ -229,7 +240,50 @@ jobs:
 
       - name: Verify
         run: |
-          cd $(ruby -e "puts RbConfig::TOPDIR + '\/lib\/ruby\/gems\/' + RbConfig::CONFIG['ruby_version'] + '\/gems\/expressir*'")
+          cd $(ruby -e "puts Gem::Specification.find_by_name('expressir').gem_dir")
+          ruby bin/rspec
+          cat .rspec_status || echo ".rspec_status was not found"
+
+  verify-ruby-linux-musl:
+    name: verify ruby gem on ruby-${{ matrix.ruby }} on alpine container
+    needs: pack-ruby
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        ruby: [ '3.2', '3.1', '3.0', '2.7' ]
+    container: ruby:${{ matrix.ruby }}-alpine
+    steps:
+      - name: Install packages
+        run: |
+          apk --no-cache --upgrade add build-base git bash tar
+
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Upgrade RubyGems
+        if: matrix.ruby == '3.0' || matrix.ruby == '2.7'
+        run: gem update --system ${{ env.RUBYGEM_VER }} --no-document
+
+      - name: Bundle
+        run: |
+          git config --global --add safe.directory $PWD
+          bundle install --jobs 4 --retry 3
+
+      - name: Download packaged gem
+        uses: actions/download-artifact@v4
+        with:
+         name: pkg-ruby
+         path: pkg
+
+      - name: Install gem
+        run: gem install -l pkg/expressir-*.gem
+
+      - name: Verify
+        run: |
+          cd $(ruby -e "puts Gem::Specification.find_by_name('expressir').gem_dir")
           ruby bin/rspec
           cat .rspec_status || echo ".rspec_status was not found"
 
@@ -267,7 +321,7 @@ jobs:
 
       - name: Verify
         run: |
-          cd $(ruby -e "puts RbConfig::TOPDIR + '\/lib\/ruby\/gems\/' + RbConfig::CONFIG['ruby_version'] + '\/gems\/expressir*'")
+          cd $(ruby -e "puts Gem::Specification.find_by_name('expressir').gem_dir")
           ruby bin/rspec
           cat .rspec_status || echo ".rspec_status was not found"
 
@@ -304,7 +358,7 @@ jobs:
 
       - name: Verify
         run: |
-          cd $(ruby -e "puts RbConfig::TOPDIR + '\/lib\/ruby\/gems\/' + RbConfig::CONFIG['ruby_version'] + '\/gems\/expressir*'")
+          cd $(ruby -e "puts Gem::Specification.find_by_name('expressir').gem_dir")
           ruby bin/rspec
           cat .rspec_status || echo ".rspec_status was not found"
 
@@ -342,7 +396,7 @@ jobs:
 
       - name: Verify
         run: |
-          cd $(ruby -e "puts RbConfig::TOPDIR + '\/lib\/ruby\/gems\/' + RbConfig::CONFIG['ruby_version'] + '\/gems\/expressir*'")
+          cd $(ruby -e "puts Gem::Specification.find_by_name('expressir').gem_dir")
           ruby bin/rspec
           cat .rspec_status || echo ".rspec_status was not found"
 
@@ -356,13 +410,23 @@ jobs:
         ruby: [ '3.2', '3.1', '3.0', '2.7' ]
     container: ruby:${{ matrix.ruby }}-alpine
     steps:
+      - name: Install packages
+        run: |
+          apk --no-cache --upgrade add build-base git bash tar
+
       - name: Checkout
         uses: actions/checkout@v4
         with:
           submodules: recursive
 
+      - name: Upgrade RubyGems
+        if: matrix.ruby == '3.0' || matrix.ruby == '2.7'
+        run: gem update --system ${{ env.RUBYGEM_VER }} --no-document
+
       - name: Bundle
-        run: bundle install --jobs 4 --retry 3
+        run: |
+          git config --global --add safe.directory $PWD
+          bundle install --jobs 4 --retry 3
 
       - name: Download packaged gem
         uses: actions/download-artifact@v4
@@ -371,10 +435,10 @@ jobs:
          path: pkg
 
       - name: Install binary gem
-        run: gem install -l pkg/expressir-*-$(ruby -e "puts RUBY_PLATFORM")-gnu.gem
+        run: gem install -l pkg/expressir-*-$(ruby -e "puts RUBY_PLATFORM").gem
 
       - name: Verify
         run: |
-          cd $(ruby -e "puts RbConfig::TOPDIR + '\/lib\/ruby\/gems\/' + RbConfig::CONFIG['ruby_version'] + '\/gems\/expressir*'")
+          cd $(ruby -e "puts Gem::Specification.find_by_name('expressir').gem_dir")
           ruby bin/rspec
           cat .rspec_status || echo ".rspec_status was not found"
